# SPDX-FileCopyrightText: Copyright (c) 2022-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: readme-automation

'on':
  workflow_dispatch:
  push:
    paths:
      - "src/eoc.js"
concurrency:
  group: readmeautomation-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Use Node
        uses: actions/setup-node@v6
        with:
          node-version: "18.x"
          check-latest: false
      - name: Clean install
        run: npm ci
      - name: Install global
        run: npm install -g
      - name: Run readme_automation script
        run: |-
          node scripts/readme_automation/readme_automation_run.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(readme): insert sections into README from CLI help"
          branch: chore/readme-automation
          title: "chore(readme): insert sections into README from CLI help"
          body: |
            This PR was automatically generated by GitHub Actions.

            - Insert sections into README from CLI help output
            - Keeps documentation in sync with the CLI
